nursery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("nurseryapp.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nurseryapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'nurseryapp'

urlpatterns = [
    path('', views.home, name='home'),    
    path('signup/', views.signup_index, name='signup'),    
    path('signup/<int:user>/', views.signup_form, name='signup_form'),    
    path('signup/post/<int:user>/', views.signup, name='post_signup'), 

    path('dashboard/', views.dashboard, name='dashboard'), 

    path('login/', views.user_login, name='login'),
    path('login_page/', TemplateView.as_view(template_name='user/login.html'), name='login_page'),
    path('logout/', views.user_logout, name='logout'),

    path('addplant_form/', views.addplant_form, name='addplant_form'),
    path('addplant/', views.addplant, name='addplant'),

    path('cart_action/<int:p_id>/<int:action>/', views.cart_action, name="cart_action"),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

nurseryapp/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    name  = models.CharField(max_length=50,)
    phone = models.CharField(max_length=20, blank=True, null=True)
    REQUIRED_FIELDS = []
    nursery = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'phone', 'password']
        labels = {
            'username': ('Email'),
        }

class Plants(models.Model):
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    stock = models.PositiveIntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.name

class PlantsForm(ModelForm):
    class Meta:
        model = Plants
        exclude=['manager']

class Order(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Plants, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name 
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    pincode = models.IntegerField(null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

nurseryapp/views.py
from django.shortcuts import render, reverse, redirect
from .models import CustomUser, UserForm, Plants, PlantsForm, Order, OrderItem, ShippingAddress
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import datetime 
import re
# from django.contrib import messages

def home(request):
    if not request.user.is_staff:
        plants = Plants.objects.all()
        return render(request, 'nurseryapp/index.html', {'plants':plants})

    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    
def signup_index(request):
    return render(request, "user/index.html")

def signup_form(request, user):
    form = UserForm()
    if user == 1:
        return render(request, "user/customer_signup.html", {'form':form})
    elif user == 2:
        return render(request, "user/manager_signup.html", {'form':form})
    else:
        return redirect('nurseryapp:signup')

def signup(request, user):
    if request.method == 'POST':
        customuser = CustomUser.objects.all()
        email = request.POST['username']
        phone = request.POST['phone']
        password = request.POST['password']
        for users in customuser:
            if email == users.username:
                return HttpResponse("Your'e already signed In.")
            if phone == users.phone:
                return HttpResponse("Phone number already registered.")
        if not re.match("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", email):
            return HttpResponse('Enter a valid email')
        if not len(phone) == 10 or not phone.isnumeric():
            return HttpResponse("Enter a valid phone number, should be 10 digits and numbers only.")
        if not len(password) > 5:
            return HttpResponse("Password should not be less than 5 characters")
        if user == 1: # user is a customer
            customer = UserForm(request.POST)
            if customer.is_valid():
                user = customer.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
                return HttpResponseRedirect(reverse('nurseryapp:login_page'))
            
        elif user == 2: #user is a manager
            manager = UserForm(request.POST)
            if manager.is_valid():
                user = manager.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
            
            nursery = request.POST['nursery']
            mgr = CustomUser.objects.get(username=email)
            mgr.is_staff=True
            mgr.nursery = nursery
            mgr.save()
            return HttpResponseRedirect(reverse('nurseryapp:login_page'))


        else:
            return HttpResponse("back to home")


def dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            myplants = Plants.objects.filter(manager=request.user)
            order_items = OrderItem.objects.filter(product__id__in=myplants.all()) #life saver line
           
            for_front = {
                'myplants':myplants,
                'orders':order_items,
            }

            return render(request, 'dashboard/manager.html', for_front)
        else:
            order = Order.objects.filter(customer=request.user, complete=True)
            order_items = OrderItem.objects.filter(order__id__in=order.all()) 
            print(order_items)
            for_front = {
                'order_items':order_items
            }
            return render(request, 'dashboard/customer.html', for_front)
    else:
        return HttpResponseRedirect(reverse('nurseryapp:login_page'))
              
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user_model = get_user_model()
            print(user_model)
            print(password)
        try:
            user = user_model.objects.get(username=username)
            print(user)
            if user.check_password(password):
                login(request, user)
                if user.is_staff:
                    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
                else:
                    return HttpResponseRedirect(reverse("nurseryapp:home"))
            else:
                return HttpResponse("Invalid password")
        except user_model.DoesNotExist:
            return HttpResponse("Invalid email")
        else:
            return HttpResponse("Not a POST request")
    else:
        return HttpResponse("You're already logged in")

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("nurseryapp:home"))

@login_required 
def addplant_form(request):
    if request.user.is_staff:
        form = PlantsForm()
        return render(request, 'dashboard/addplant_form.html', {'form':form})

@login_required
def addplant(request):
    if request.user.is_staff and request.method == 'POST':
        plant = PlantsForm(request.POST, request.FILES)
        if plant.is_valid:
            p = plant.save(commit=False)
            p.manager = request.user 
            plant.save()
            return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    else:
        return HttpResponse("Waait a min, Who Are You ?")

@login_required(login_url='nurseryapp:login_page')
def cart_action(request, p_id, action):
    user = request.user
    product = Plants.objects.get(id=p_id)
    order, created = Order.objects.get_or_create(customer=user, complete=False)
    orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)   
    if action == 1: # for add item
        orderitem.quantity += 1
    elif action == 0: # For Remove Item
        orderitem.quantity -= 1

    orderitem.save()

    if orderitem.quantity <= 0:
        orderitem.delete()
    
    return HttpResponseRedirect(reverse('nurseryapp:cart'))

@login_required(login_url='nurseryapp:login_page')
def cart(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/cart.html', {'items':items, 'order':order})


@login_required(login_url='nurseryapp:login_page')
def checkout(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/checkout.html', {'items':items, 'order':order})

@login_required(login_url='nurseryapp:login_page')
def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()

    customer = request.user

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    total = order.get_cart_total
    order.transaction_id = transaction_id

    order.complete = True
    order.save()    


    ShippingAddress.objects.create(
        customer = customer,
        order = order,
        address = request.POST['address'],
        city = request.POST['city'],
        state = request.POST['state'],
        pincode = request.POST['pincode'],
    )

    return HttpResponseRedirect(reverse('nurseryapp:dashboard'))

nurseryapp/templates/nurseryapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="../../../media/css/style.css">
    <title>Nursery</title>

<style>
  .text-block {
  position: absolute;
  top: 350px;
  left: 100px;
  color: white;
  padding-left: 20px;
  padding-right: 20px;
}

html{
  scroll-behavior: smooth;
}
</style>

</head>
<body>
    
  <nav class="nav-center white" style="min-height: 150px;">
    <div class="nav-wrapper">
        <a href="{% url 'nurseryapp:home' %}" class="brand-logo left"><img src="../../../media/logo/plant.svg" width="100%" height="100px"></a>
        <ul>
          <li><a href="#home" class="black-text bold"><b>Home</a></li>
          <li><a href="#shop" class="black-text">Shop</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'nurseryapp:logout' %}" class="black-text">LogOut</a></li>
          {% else %}
            <li><a href="{% url 'nurseryapp:signup' %}" class="black-text">SignUp</a></li>
            <li><a href="{% url 'nurseryapp:login_page' %}" class="black-text">LogIn</a></li>              
          {% endif %}
          
          <div id="home-icons" class="right" style="margin-top: 7px;">
              <li><a class="material-icons black-text">search</li>
              <li><a class="material-icons black-text" href="{% url 'nurseryapp:dashboard' %}">account_circle</li>
              <li><a class="material-icons black-text" href="{% url 'nurseryapp:cart' %}">shopping_cart</a></li>
          </div>
        </ul>
    </div>
  </nav>

  <div>
    <img src="../../../media/background/bg1.jpg" alt="bg1" style="filter:brightness(55%); height: 475px; width: 100%;">
    <div class="text-block">
      <h4>Plants Nursery</h4>
      <p>Naturalize your envirnoment</p>
    </div>      
  </div>
   

  {% block card %}
  {% endblock %}



  <footer class="page-footer light-green darken-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Nursery</h5>
          <p class="grey-text text-lighten-4">This website is for the showcase purpose only.</p>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © All images are taken from Unsplash.com <br>
      Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a>
      <a  href="https://www.github.com/shreyashsrivastava" class="grey-text text-lighten-4 right">Github Link</a>
      </div>
    </div>
  </footer>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

nurseryapp/templates/nurseryapp/cart.html
{% extends 'user/base.html' %}

{% block content %}

{% if order.get_cart_items is not 0 %}
<div id='cart-card' class="container col s12 m12 l12">  
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">      
          <div class="row">
            <div class="col l4 m4 s12">
              Items: {{ order.get_cart_items }}
            </div>
            <div class="col l4 m4 s12">
              Total: Rs. {{ order.get_cart_total|floatformat:2}}
            </div>
            <div class="col l4 m4 s12">
              <a href="{% url 'nurseryapp:checkout' %}" class="waves-effect waves-light btn right">Checkout</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% else %}
  <h2 class="center">Oops! there's nothing in the cart</h2>
{% endif %}

{% for item in items %}
<div id='cart-card' class="container col s12 m12 l12">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content">
        <div class="row">
          <div class="col l3 m3 s3">
            <img src="{{ item.product.image.url }}" alt="" height="100px" width="100px">
          </div>
          <div class="col l3 m3 s3">
            {{ item.product.name|title }}<br>
            {{ item.product.description }}<br>
            Rs. {{ item.product.price }}
          </div>
          <div class="col l3 m3 s3">
            Quantity:<br>
            <a class="btn btn-small btn-flat" href="{% url 'nurseryapp:cart_action' item.product.id 0 %}"><i class="material-icons">remove</i></a>
              {{ item.quantity }}
            <a class="btn btn-small btn-flat" href="{% url 'nurseryapp:cart_action' item.product.id 1 %}"><i class="material-icons">add</i></a> 
          </div>
          <div class="col l3 m3 s3">
           Price:<br>Rs. {{ item.get_total }}
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

nurseryapp/templates/nurseryapp/checkout.html
{% extends 'user/base.html' %}

{% block content %}

{% if items %}

<div id='cart-card' class="container col s12 m12 l12">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div>
          
          <a class="btn " style="display: inline-block; margin-top: 10px;" href="{% url 'nurseryapp:cart' %}">Back To Cart</a><br><br>
          </div>
          <div class="row">
            <div class="col l8 m12 s12">
                <div class="row">                 
                  <form class="col s12" id="form" method="POST" action="{% url 'nurseryapp:process_order' %}">
                    {% csrf_token %}
                    <div id="shipping-info">
                      <h5 class="left-align" style="display: inline-block;">Enter Address</h5> 
                    <div class="row">                     
                      <div class="input-field col s6">
                        <input id="address" type="text" class="validate" name="address" required>
                        <label for="address">Address</label>
                      </div>                  
                      <div class="input-field col s6">
                        <input id="city" type="text" class="validate" name="city" required>
                        <label for="city">City</label>
                      </div>
                    </div>  
                    <div class="row">
                      <div class="input-field col s6">
                        <input id="state" type="text" class="validate" name="state" required>
                        <label for="state">State</label>
                      </div>                  
                      <div class="input-field col s6">
                        <input id="pincode" type="number" class="validate" name="pincode" required>
                        <label for="pincode">PinCode</label>
                      </div>
                      </div>
                    </div>  

                    <input class="btn" type="submit" value="Proceed for payment"> 
                    
                  </form>                                
                </div>
            </div>
           
            <div class="col l4 m12 s12" id="order-summary">
              
              <h5>Order Summary</h5><hr><br>
              {% for item in items %}
              <div class="row">
                <div class="col l3 m3 s3">
                  <img src="{{ item.product.image.url }}" alt="" height="50px" width="50px">
                </div>
                <div class="col l3 m3 s3">
                  "{{ item.product.name|title }}"
                </div>
                <div class="col l3 m3 s3">
                  {{ item.quantity }} Pot
                </div>
                <div class="col l3 m3 s3">
                  Rs. {{ item.get_total }}
                </div>
              </div>
              {% endfor %}
              <hr>
              <p>Total Plants: {{ order.get_cart_items }}</p><br>
              <p>Total Price: Rs. {{ order.get_cart_total }}</p>
              <hr>             
            </div>  
          </div> 
        </div>
      </div>
    </div>
</div>

{% else %}

<h2>Oops! there's nothing in the cart</h2>

{% endif %}

{% endblock %}

nurseryapp/templates/nurseryapp/index.html
{% extends 'nurseryapp/base.html' %}

{% block card %}

<div id='shop' class="container row">
  {% for plant in plants %}
    <div class="center col s12 m12 l4" style="margin-top: 50px;">
      <div class="card">
        <div class="card-image">
          <img src="{{ plant.image.url }}" style="height: 300px;">
          <span class="card-title white-text">{{ plant.name|title }}</span>
          <a class="btn-floating halfway-fab waves-effect waves-light green darken-4" href="{% url 'nurseryapp:cart_action' plant.id 1 %}"><i class="material-icons">add_shopping_cart</i></a>
        </div>
        <div class="card-content">
          <left>
            <p>{{ plant.description }}</p>
            <p>By {{ plant.manager.nursery }}</p>
            <p>Rs. {{ plant.price }}</p>
          </left>
        </div>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}