nursery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("nurseryapp.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nurseryapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'nurseryapp'

urlpatterns = [
    path('', views.home, name='home'),    
    path('signup/', views.signup_index, name='signup'),    
    path('signup/<int:user>/', views.signup_form, name='signup_form'),    
    path('signup/post/<int:user>/', views.signup, name='post_signup'), 

    path('dashboard/', views.dashboard, name='dashboard'), 

    path('login/', views.user_login, name='login'),
    path('login_page/', TemplateView.as_view(template_name='user/login.html'), name='login_page'),
    path('logout/', views.user_logout, name='logout'),

    path('addplant_form/', views.addplant_form, name='addplant_form'),
    path('addplant/', views.addplant, name='addplant'),

    path('cart_action/<int:p_id>/<int:action>/', views.cart_action, name="cart_action"),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

nurseryapp/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    name  = models.CharField(max_length=50,)
    phone = models.CharField(max_length=20, blank=True, null=True)
    REQUIRED_FIELDS = []
    nursery = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'phone', 'password']
        labels = {
            'username': ('Email'),
        }

class Plants(models.Model):
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    stock = models.PositiveIntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.name

class PlantsForm(ModelForm):
    class Meta:
        model = Plants
        exclude=['manager']

class Order(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Plants, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name 
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    pincode = models.IntegerField(null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

nurseryapp/views.py
from django.shortcuts import render, reverse, redirect
from .models import CustomUser, UserForm, Plants, PlantsForm, Order, OrderItem, ShippingAddress
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import datetime 
import re
# from django.contrib import messages

def home(request):
    if not request.user.is_staff:
        plants = Plants.objects.all()
        return render(request, 'nurseryapp/index.html', {'plants':plants})

    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    
def signup_index(request):
    return render(request, "user/index.html")

def signup_form(request, user):
    form = UserForm()
    if user == 1:
        return render(request, "user/customer_signup.html", {'form':form})
    elif user == 2:
        return render(request, "user/manager_signup.html", {'form':form})
    else:
        return redirect('nurseryapp:signup')

def signup(request, user):
    if request.method == 'POST':
        customuser = CustomUser.objects.all()
        email = request.POST['username']
        phone = request.POST['phone']
        password = request.POST['password']
        for users in customuser:
            if email == users.username:
                return HttpResponse("Your'e already signed In.")
            if phone == users.phone:
                return HttpResponse("Phone number already registered.")
        if not re.match("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", email):
            return HttpResponse('Enter a valid email')
        if not len(phone) == 10 or not phone.isnumeric():
            return HttpResponse("Enter a valid phone number, should be 10 digits and numbers only.")
        if not len(password) > 5:
            return HttpResponse("Password should not be less than 5 characters")
        if user == 1: # user is a customer
            customer = UserForm(request.POST)
            if customer.is_valid():
                user = customer.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
                return HttpResponseRedirect(reverse('nurseryapp:login_page'))
            
        elif user == 2: #user is a manager
            manager = UserForm(request.POST)
            if manager.is_valid():
                user = manager.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
            
            nursery = request.POST['nursery']
            mgr = CustomUser.objects.get(username=email)
            mgr.is_staff=True
            mgr.nursery = nursery
            mgr.save()
            return HttpResponseRedirect(reverse('nurseryapp:login_page'))


        else:
            return HttpResponse("back to home")


def dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            myplants = Plants.objects.filter(manager=request.user)
            order_items = OrderItem.objects.filter(product__id__in=myplants.all()) #life saver line
           
            for_front = {
                'myplants':myplants,
                'orders':order_items,
            }

            return render(request, 'dashboard/manager.html', for_front)
        else:
            order = Order.objects.filter(customer=request.user, complete=True)
            order_items = OrderItem.objects.filter(order__id__in=order.all()) 
            print(order_items)
            for_front = {
                'order_items':order_items
            }
            return render(request, 'dashboard/customer.html', for_front)
    else:
        return HttpResponseRedirect(reverse('nurseryapp:login_page'))
              
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user_model = get_user_model()
            print(user_model)
            print(password)
        try:
            user = user_model.objects.get(username=username)
            print(user)
            if user.check_password(password):
                login(request, user)
                if user.is_staff:
                    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
                else:
                    return HttpResponseRedirect(reverse("nurseryapp:home"))
            else:
                return HttpResponse("Invalid password")
        except user_model.DoesNotExist:
            return HttpResponse("Invalid email")
        else:
            return HttpResponse("Not a POST request")
    else:
        return HttpResponse("You're already logged in")

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("nurseryapp:home"))

@login_required 
def addplant_form(request):
    if request.user.is_staff:
        form = PlantsForm()
        return render(request, 'dashboard/addplant_form.html', {'form':form})

@login_required
def addplant(request):
    if request.user.is_staff and request.method == 'POST':
        plant = PlantsForm(request.POST, request.FILES)
        if plant.is_valid:
            p = plant.save(commit=False)
            p.manager = request.user 
            plant.save()
            return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    else:
        return HttpResponse("Waait a min, Who Are You ?")

@login_required(login_url='nurseryapp:login_page')
def cart_action(request, p_id, action):
    user = request.user
    product = Plants.objects.get(id=p_id)
    order, created = Order.objects.get_or_create(customer=user, complete=False)
    orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)   
    if action == 1: # for add item
        orderitem.quantity += 1
    elif action == 0: # For Remove Item
        orderitem.quantity -= 1

    orderitem.save()

    if orderitem.quantity <= 0:
        orderitem.delete()
    
    return HttpResponseRedirect(reverse('nurseryapp:cart'))

@login_required(login_url='nurseryapp:login_page')
def cart(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/cart.html', {'items':items, 'order':order})


@login_required(login_url='nurseryapp:login_page')
def checkout(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/checkout.html', {'items':items, 'order':order})

@login_required(login_url='nurseryapp:login_page')
def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()

    customer = request.user

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    total = order.get_cart_total
    order.transaction_id = transaction_id

    order.complete = True
    order.save()    


    ShippingAddress.objects.create(
        customer = customer,
        order = order,
        address = request.POST['address'],
        city = request.POST['city'],
        state = request.POST['state'],
        pincode = request.POST['pincode'],
    )

    return HttpResponseRedirect(reverse('nurseryapp:dashboard'))

nurseryapp/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>SignUp</title>
</head>
<body bgcolor="whitesmoke">
  
  <nav class="white">
    <div class="nav-wrapper">
      <a href="{% url 'nurseryapp:home' %}"><img src="../../../media/logo/plant.svg" class="brand-logo" height="55px" width="60px"></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="black-text" href="{% url 'nurseryapp:home' %}">Home</a></li>
        <li><a class="black-text" href="{% url 'nurseryapp:home' %}/#shop">Shop</a></li>
        {% if user.is_authenticated %}
        <li><a class="black-text" href="{% url 'nurseryapp:logout' %}">LogOut</a></li>
        {% else %}
        <li><a class="black-text" href="{% url 'nurseryapp:login_page' %}">LogIn</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <footer class="page-footer light-green darken-1" style="bottom: 0px;">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="black-text">Nursery</h5>
          <p class="grey-text text-darken-4">This website is for the showcase purpose only.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="black-text">Links</h5>
          <ul>
            <li><a class="grey-text text-darken-4" href="{% url 'nurseryapp:home' %}">Home</a></li>
            <li><a class="grey-text text-darken-4" href="{% url 'nurseryapp:signup' %}">SignUp</a></li>
            <li><a class="grey-text text-darken-4" href="{% url 'nurseryapp:login_page' %}">LogIn</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2020 Nursery 
      <a  href="https://www.github.com/shreyashsrivastava" class="grey-text text-lighten-4 right">Github Link</a>

      </div>
    </div>
  </footer>
      


  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

nurseryapp/templates/user/customer_signup.html
{% extends 'user/base.html' %}

{% block content %}

<h2 class="header center">Customer SignUp</h2>
<div class="container">
<form class="card" method="POST" action="{% url 'nurseryapp:post_signup' 1 %}"  style="padding:25px;">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn" type="submit" value="SignUp"> 
</form>
</div>
  {% endblock %}

nurseryapp/templates/user/index.html
{% extends 'user/base.html' %} 


{% block content %}

  <div class="row container" style="margin-top: 25px;">
    <div class="col s12 m6">
      <div class="card grey lighten-5" style="height: 400px;">
        <div class="center card-content black-text">
          <span class="card-title">Customer</span>
          <i class="large material-icons">people</i>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="center card-action">
          <a class="btn" href="{% url 'nurseryapp:signup_form' 1 %}">Customer SignUp</a>
        </div>
      </div>
    </div>

    <div class="col s12 m6">
      <div class="card grey lighten-5" style="height: 400px;">
        <div class="center card-content black-text">
          <span class="card-title">Nursery</span>
          <i class="large material-icons">settings</i>
          <p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="center card-action">
          <a class="btn" href="{% url 'nurseryapp:signup_form' 2 %}">Nursery SignUp</a>
        </div>
      </div>
    </div>

  </div>

  {% endblock %}


 

nurseryapp/templates/user/login.html
{% extends 'user/base.html' %}

<!-- {% block title %}Login{% endblock %} -->

{% block content %}
{% if not user.is_authenticated %}

<div class="container">
  <h2>Login</h2>
  <form class="card" method="POST" action="{% url 'nurseryapp:login' %}" style="padding: 25px;">
    {% csrf_token %}
    Email:
    <input type="email" name="username"><br>
    Password:
    <input type="password" name=password value=""><br>
    <button class="btn" type="submit">Login</button>
  </form>
</div>

{% else %}
  <h2>You're already loggedIn</h2>
{% endif %}
{% endblock %}

nurseryapp/templates/user/manager_signup.html
{% extends 'user/base.html' %}

{% block content %}

<h2 class="header center">Nursery SignUp</h2>

<div class="container">
    <form class="card" method="POST" action="{% url 'nurseryapp:post_signup' 2 %}" style="padding:25px;">
        {% csrf_token %}
        {{form.as_p}}
        <div class="input-field col s12">
            <input name="nursery" id="nursery" type="text" class="validate" required>
            <label for="nursery">Nursery</label>
        </div>
        <!-- <input type="text" name="nursery" value="" placeholder="Nursery" /> -->
        <input class="btn" type="submit" value="SignUp">
    </form> 
</div>

{% endblock %}