nursery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("nurseryapp.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nurseryapp/urls.py
from django.urls import path, include
from . import views
from django.views.generic import TemplateView

app_name = 'nurseryapp'

urlpatterns = [
    path('', views.home, name='home'),    
    path('signup/', views.signup_index, name='signup'),    
    path('signup/<int:user>/', views.signup_form, name='signup_form'),    
    path('signup/post/<int:user>/', views.signup, name='post_signup'), 

    path('dashboard/', views.dashboard, name='dashboard'), 

    path('login/', views.user_login, name='login'),
    path('login_page/', TemplateView.as_view(template_name='user/login.html'), name='login_page'),
    path('logout/', views.user_logout, name='logout'),

    path('addplant_form/', views.addplant_form, name='addplant_form'),
    path('addplant/', views.addplant, name='addplant'),

    path('cart_action/<int:p_id>/<int:action>/', views.cart_action, name="cart_action"),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

nurseryapp/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    name  = models.CharField(max_length=50,)
    phone = models.CharField(max_length=20, blank=True, null=True)
    REQUIRED_FIELDS = []
    nursery = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class UserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['name', 'username', 'phone', 'password']
        labels = {
            'username': ('Email'),
        }

class Plants(models.Model):
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    stock = models.PositiveIntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.name

class PlantsForm(ModelForm):
    class Meta:
        model = Plants
        exclude=['manager']

class Order(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderItem(models.Model):
    product = models.ForeignKey(Plants, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name 
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    pincode = models.IntegerField(null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

nurseryapp/views.py
from django.shortcuts import render, reverse, redirect
from .models import CustomUser, UserForm, Plants, PlantsForm, Order, OrderItem, ShippingAddress
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
import datetime 
import re
# from django.contrib import messages

def home(request):
    if not request.user.is_staff:
        plants = Plants.objects.all()
        return render(request, 'nurseryapp/index.html', {'plants':plants})

    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    
def signup_index(request):
    return render(request, "user/index.html")

def signup_form(request, user):
    form = UserForm()
    if user == 1:
        return render(request, "user/customer_signup.html", {'form':form})
    elif user == 2:
        return render(request, "user/manager_signup.html", {'form':form})
    else:
        return redirect('nurseryapp:signup')

def signup(request, user):
    if request.method == 'POST':
        customuser = CustomUser.objects.all()
        email = request.POST['username']
        phone = request.POST['phone']
        password = request.POST['password']
        for users in customuser:
            if email == users.username:
                return HttpResponse("Your'e already signed In.")
            if phone == users.phone:
                return HttpResponse("Phone number already registered.")
        if not re.match("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", email):
            return HttpResponse('Enter a valid email')
        if not len(phone) == 10 or not phone.isnumeric():
            return HttpResponse("Enter a valid phone number, should be 10 digits and numbers only.")
        if not len(password) > 5:
            return HttpResponse("Password should not be less than 5 characters")
        if user == 1: # user is a customer
            customer = UserForm(request.POST)
            if customer.is_valid():
                user = customer.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
                return HttpResponseRedirect(reverse('nurseryapp:login_page'))
            
        elif user == 2: #user is a manager
            manager = UserForm(request.POST)
            if manager.is_valid():
                user = manager.save(commit=False)
                user.set_password(request.POST['password'])
                user.save()
            
            nursery = request.POST['nursery']
            mgr = CustomUser.objects.get(username=email)
            mgr.is_staff=True
            mgr.nursery = nursery
            mgr.save()
            return HttpResponseRedirect(reverse('nurseryapp:login_page'))


        else:
            return HttpResponse("back to home")


def dashboard(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            myplants = Plants.objects.filter(manager=request.user)
            order_items = OrderItem.objects.filter(product__id__in=myplants.all()) #life saver line
           
            for_front = {
                'myplants':myplants,
                'orders':order_items,
            }

            return render(request, 'dashboard/manager.html', for_front)
        else:
            order = Order.objects.filter(customer=request.user, complete=True)
            order_items = OrderItem.objects.filter(order__id__in=order.all()) 
            print(order_items)
            for_front = {
                'order_items':order_items
            }
            return render(request, 'dashboard/customer.html', for_front)
    else:
        return HttpResponseRedirect(reverse('nurseryapp:login_page'))
              
def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user_model = get_user_model()
            print(user_model)
            print(password)
        try:
            user = user_model.objects.get(username=username)
            print(user)
            if user.check_password(password):
                login(request, user)
                if user.is_staff:
                    return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
                else:
                    return HttpResponseRedirect(reverse("nurseryapp:home"))
            else:
                return HttpResponse("Invalid password")
        except user_model.DoesNotExist:
            return HttpResponse("Invalid email")
        else:
            return HttpResponse("Not a POST request")
    else:
        return HttpResponse("You're already logged in")

def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("nurseryapp:home"))

@login_required 
def addplant_form(request):
    if request.user.is_staff:
        form = PlantsForm()
        return render(request, 'dashboard/addplant_form.html', {'form':form})

@login_required
def addplant(request):
    if request.user.is_staff and request.method == 'POST':
        plant = PlantsForm(request.POST, request.FILES)
        if plant.is_valid:
            p = plant.save(commit=False)
            p.manager = request.user 
            plant.save()
            return HttpResponseRedirect(reverse("nurseryapp:dashboard"))
    else:
        return HttpResponse("Waait a min, Who Are You ?")

@login_required(login_url='nurseryapp:login_page')
def cart_action(request, p_id, action):
    user = request.user
    product = Plants.objects.get(id=p_id)
    order, created = Order.objects.get_or_create(customer=user, complete=False)
    orderitem, created = OrderItem.objects.get_or_create(order=order, product=product)   
    if action == 1: # for add item
        orderitem.quantity += 1
    elif action == 0: # For Remove Item
        orderitem.quantity -= 1

    orderitem.save()

    if orderitem.quantity <= 0:
        orderitem.delete()
    
    return HttpResponseRedirect(reverse('nurseryapp:cart'))

@login_required(login_url='nurseryapp:login_page')
def cart(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/cart.html', {'items':items, 'order':order})


@login_required(login_url='nurseryapp:login_page')
def checkout(request):
    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    return render(request, 'nurseryapp/checkout.html', {'items':items, 'order':order})

@login_required(login_url='nurseryapp:login_page')
def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()

    customer = request.user

    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    total = order.get_cart_total
    order.transaction_id = transaction_id

    order.complete = True
    order.save()    


    ShippingAddress.objects.create(
        customer = customer,
        order = order,
        address = request.POST['address'],
        city = request.POST['city'],
        state = request.POST['state'],
        pincode = request.POST['pincode'],
    )

    return HttpResponseRedirect(reverse('nurseryapp:dashboard'))

nurseryapp/templates/dashboard/addplant_form.html
{% extends 'user/base.html' %}

{% block content %}

<h2 class="header center">Add Plant</h2>
<div class="container">
<form class="card" method="POST" action="{% url 'nurseryapp:addplant' %}" enctype="multipart/form-data" style="padding:25px;">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn" type="submit" value="Add"> 
</form>
</div>

{% endblock %}

nurseryapp/templates/dashboard/customer.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container row">

<h2>Orders Placed</h2>

{% for plant in order_items %}

<div class=" col s12 m12 l4" style="margin-top: 50px;">
    <div class="center card">
      <div class="card-image">
        <img src="{{ plant.product.image.url }}" style="height: 300px;">
        <span class="card-title white-text">{{ plant.product.name|title }}</span>
      </div>
      <div class="card-content">
        <left>
          <p>{{ plant.product.description }}</p>
          <p>By {{ plant.product.manager.nursery }}</p>
          <p>Rs. {{ plant.product.price }}</p>
          <p>Quantity: {{ plant.quantity }}</p>
        </left>
      </div>
    </div>
  </div>

{% endfor %}
</div>
{% endblock %}

nurseryapp/templates/dashboard/manager.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container row">
    <h3 style="padding-left:10px ;">My Plants</h3>
    <div class=" col s12 m12 l4" style="margin-top: 50px;">
        <div class="center card">
          <div class="card-image">
            <a href="{% url 'nurseryapp:addplant_form' %}"><img src="../../../media/background/add.jpg" style="height: 300px;"></a>
            <div class="card-content" style="height: 183px;">
                <h5>Add a Plant</h5>
            </div>
          </div>
        </div>
      </div>
      {% for plant in myplants %}

    <div class=" col s12 m12 l4" style="margin-top: 50px;">
        <div class="center card">
          <div class="card-image">
            <img src="{{ plant.image.url }}" style="height: 300px;">
            <span class="card-title white-text">{{ plant.name|title }}</span>
          </div>
          <div class="card-content">
            <left>
              <p>{{ plant.description }}</p>
              <p>By {{ plant.manager.nursery }}</p>
              <p>Rs. {{ plant.price }}</p>
            </left>
          </div>
          <div class="card-action">
            <a class="btn light-green darken-2" href="#">Click to know more</a>
          </div>
        </div>
      </div>
      {% endfor %}
</div>

<div class="container row">
  <h3 style="padding-left:10px ;">Orders Recieved</h3>
  
    {% for order in orders %}

  <div class=" col s12 m12 l4" style="margin-top: 50px;">
      <div class="center card">
        <div class="card-image">
          <img src="{{ order.product.image.url }}" style="height: 300px;">
          <span class="card-title black-text"></span>
        </div>
        <div class="card-content">
          <left>
            <p>{{ order.product.description }}</p>
            <p>Quantity: {{ order.quantity }}</p>
            <p>Amount: {{ order.get_total }}</p>
            <p>Customer: {{ order.order.customer }}</p>
            <p>Address: {{ address }}</p>
          </left>
        </div>
  
      </div>
    </div>
    {% endfor %}

</div>

{% endblock %}